name: Aghisna OSS
on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-22.04

    steps:
    - name: setting configurasi
      uses: actions/checkout@v3

    - name: setting Runner
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev \
    - name: kompile krunulll....
      run: |
          curl https://raw.githubusercontent.com/RooGhz720/RooGhz720/main/.oss.sh > .oss.sh
          chmod +x .oss.sh
          bash .oss.sh
      shell: bash
      env:
         CHATID: ${{ secrets.CHAT_ID }}
         API_BOT: ${{ secrets.BOT_API }}
         TYPE_KERNEL: ${{ secrets.EZA }}

